#cloud-config
users:
  - name: j0e1in
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjuVmdynduTrOq6Z9/GPkjc6zhtPjnOuOOU2AS+b0Idi+SbNwFVZfN6tib6R5Y76gGdPTZA2Qrf/ZpRBQuEycaFS07CGuIn42RNCE7G0XdGIAuGkHBXQ8Z3T++V8FoMTf/GdgzUXEOVSVFDPOSPCajorEC6se7sgB36yqDywWGvTFV+Wq/929WWmCitbF97L1Y5mtF/phRjGnfduW73wrSHsXmBfYJoCfXUQ4RGaZeFDPicDpPDMVdi4rcsSw2jwUpXWiAPHF4OjW77pABHgmgtV0Kk3sBVVm0X8/GCeXbTUJTF5QHsvM9Rn5sDP+crrBEA49wprFZEhVRrkNBV5rV j0e1in@dell-xps-ubuntu

package_upgrade: true
packages:
  - htop
  - zip

runcmd:
  # Giving non-root access ( reboot to take effect)
  - "sudo usermod -aG docker $(whoami)"

  # docker swarm init
  - "ADDR=$(/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')"
  - "docker swarm init --advertise-addr $ADDR"

  # Install gcloud
  - "export CLOUD_SDK_REPO=\"cloud-sdk-$(lsb_release -c -s)\""
  - "echo \"deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main\" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list"
  - "curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
  - "sudo apt-get update && sudo apt-get install -y google-cloud-sdk"

power_state:
  delay: "now"
  mode: reboot
  message: First reboot
  condition: True