# For building and pushing image
version: '3.5'
services:
  main:
    build: ./
    image: gcr.io/docker-reghub/pyct
    deploy:
      replicas: 0


secrets:
  keys.json:
    file: ./private/keys.json
  redis-passwd:
    file: ./private/redis-passwd