version: '3.3'
services:
  pyct:
    build:
      context: ./
  pyct_trade:
    build:
      context: ./docker/trade
    command: "--enable-api --log"
    volumes:
      - ./log:/app/log
      - ./settings:/app/settings
    networks:
      - mongo_net
    secrets:
      - source: keys.json
        target: /app/private/keys.json
      - source: fullchain.pem
        target: /app/private/fullchain.pem
      - source: privkey.pem
        target: /app/private/privkey.pem
    depends_on:
      - pyct
      - mongo
  mongo:
    image: mongo:3.6
    networks:
      - mongo_net
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null --quiet --auth

networks:
  mongo_net:

volumes:
  mongo_data:
    external: true

secrets:
  keys.json:
    file: ./private/keys.json
  fullchain.pem:
    file: ./private/fullchain.pem
  privkey.pem:
    file: ./private/privkey.pem