version: '3.5'
services:
  ohlcv:
    image: gcr.io/docker-reghub/pyct
    command: >
              --ohlcv-stream
              --mongo-host=mongo
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./settings:/app/settings:ro
    networks:
      - mongo_net
    secrets:
      - source: keys.json
        target: /app/private/keys.json
    depends_on:
      - mongo
    restart: always
    deploy:
      replicas: 1
  mongo:
    image: mongo:3.6
    command: mongod --smallfiles --logpath=/dev/null --quiet --auth
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_net
    ports:
      - 27017:27017
    restart: always
    deploy:
      replicas: 1
  redis:
    image: redis:4-alpine
    command: >
              sh -c
              "docker-entrypoint.sh
              --requirepass \"$$(cat /run/secrets/redis-passwd)\""
    volumes:
      - redis_data:/data
      - ./settings/redis.conf:/etc/redis/redis.conf
    networks:
      - redis_net
    ports:
      - 6379:6379
    secrets:
      - redis-passwd
    restart: always
    deploy:
      replicas: 1


networks:
  mongo_net:
    external: true
  redis_net:
    external: true

volumes:
  mongo_data:
    external: true
  redis_data:
    external: true

secrets:
  keys.json:
    file: ./private/keys.json
  redis-passwd:
    file: ./private/redis-passwd