version: '3.5'
services:
  fetch_trades:
    image: gcr.io/docker-reghub/pyct
    command: "--fetch-trades"
    volumes:
      - ../../settings:/app/settings
    networks:
      - mongo_net
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    networks:
      - mongo_net
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null --quiet --auth

networks:
  mongo_net:

volumes:
  mongo_data:
    external: true