FROM python:3.6-alpine

RUN adduser -S admin

WORKDIR /app

RUN apk update && apk add \
    g++ \
    git \
    make \
    wget

RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
    tar xvf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib && \
    ./configure --prefix=/usr && \
    make && \
    make install  && \
    cd ..  && \
    rm -rf ta-lib && \
    rm ta-lib-0.4.0-src.tar.gz

COPY ./requirements-docker.txt /app/

RUN pip install -r requirements-docker.txt && \
    pip install ta-lib  # this module needs to be installed after numpy

# RUN git clone https://github.com/matplotlib/mpl_finance.git  && \
#     cd mpl_finance  && \
#     python setup.py install  && \
#     cd ..  && \
#     rm -rf mpl_finance

COPY . /app

USER admin

CMD ["python", "scripts/trading/start_trader.py"]