version: '3.5'
services:
  optimize:
    image: gcr.io/docker-reghub/pyct
    command: >
              --optimize-params optimize
              --name="$${INDICATOR_NAME}"
              --mongo-host="$${REMOTE_MONGO_IP}"
              --symbols="$${OPTIMIZE_SYMBOLS}"
    env_file:
      - ../.env
    volumes:
      - ../log:/app/log
      - ../settings:/app/settings:ro
    ports:
      - "8000:8000"
    secrets:
      - source: keys.json
        target: /app/private/keys.json
    deploy:
      replicas: 1


secrets:
  keys.json:
    file: ../private/keys.json