version: '3.5'
services:
  mongo:
    image: gcr.io/docker-reghub/mongo
    env_file:
      - ../.env
    volumes:
      - mongo_data:/data/db
      - ../../log:/log
      - ../settings:/app/settings:ro
    networks:
      - mongo_net_swarm
    ports:
      - 27017:27017
    secrets:
      - source: mongod.pem
        target: /app/private/ssl/mongod.pem
      - source: ca.pem
        target: /app/private/ssl/ca.pem
    deploy:
      replicas: 1
  redis:
    image: redis:4-alpine
    command: >
              sh -c
              "docker-entrypoint.sh
              /etc/redis/redis.conf
              --requirepass \"$$(cat /run/secrets/redis-passwd)\""
    volumes:
      - redis_data:/data
      - ../../log:/log
      - ../settings/redis.conf:/etc/redis/redis.conf
    networks:
      - redis_net_swarm
    ports:
      - 6379:6379
    secrets:
      - redis-passwd
    deploy:
      replicas: 1


networks:
  mongo_net_swarm:
    external: true
  redis_net_swarm:
    external: true

volumes:
  mongo_data:
    external: true
  redis_data:
    external: true

secrets:
  keys.json:
    file: ../private/keys.json
  redis-passwd:
    file: ../private/redis-passwd
  mongod.pem:
    file: ../private/ssl/mongod.pem
  ca.pem:
    file: ../private/ssl/ca.pem