version: '3.5'
services:
  main:
    image: gcr.io/docker-reghub/pyct
    command: >
              ${PYCT_CMD}
    env_file:
      - ../.env
    environment:
      - PYCT_MODE=production
    volumes:
      - ../data:/app/data
      - ../../log:/log
      - ../settings:/app/settings:ro
    networks:
      - mongo_net_swarm
      - redis_net_swarm
    ports:
      - "8000:8000"
    secrets:
      - source: keys.json
        target: /app/private/keys.json
      - source: fullchain.pem
        target: /app/private/ssl/fullchain.pem
      - source: privkey.pem
        target: /app/private/ssl/privkey.pem
      - source: mongod.pem
        target: /app/private/ssl/mongod.pem
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5


networks:
  mongo_net_swarm:
    external: false
  redis_net_swarm:
    external: false

secrets:
  keys.json:
    file: ../private/keys.json
  fullchain.pem:
    file: ../private/ssl/fullchain.pem
  privkey.pem:
    file: ../private/ssl/privkey.pem
  mongod.pem:
    file: ../private/ssl/mongod.pem