version: '3.5'
services:
  ohlcv:
    image: gcr.io/docker-reghub/pyct
    command: >
              --ohlcv-stream
              --mongo-host=mongo
    volumes:
      - ../data:/app/data
      - ../log:/app/log
      - ../settings:/app/settings:ro
    networks:
      - mongo_net_swarm
    secrets:
      - source: keys.json
        target: /app/private/keys.json
    deploy:
      replicas: 1

networks:
  mongo_net_swarm:
    external: true

volumes:
  mongo_data:
    external: true

secrets:
  keys.json:
    file: ../private/keys.json
